apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: connectapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AB-ArithmeticBird/argocd-kafka.git
    targetRevision: HEAD
    path: connect-cluster/connect-app
  destination:
    name: in-cluster
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true