apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-schema-registry
  namespace: default
  labels:
    app: my-schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-schema-registry
  template:
    metadata:
      labels:
        app: my-schema-registry
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: my-schema-registry
          image:  confluentinc/cp-schema-registry:6.0.1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: schema-registry-config
