apiVersion: v1
kind: Service
metadata:
  name: my-schema-registry
  namespace: default
spec:
  ports:
    - name: my-schema-registry
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: my-schema-registry
