apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect-app
  namespace: default
  labels:
    app: kafka-connect-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connect-app
  template:
    metadata:
      labels:
        app: connect-app
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: connect-app
          image: ghcr.io/ab-arithmeticbird/argocd-kafka/abird-connect:0.6
          ports:
            - name: http
              containerPort: 1337
          envFrom:
            - configMapRef:
                name: connect-config
      imagePullSecrets:
        - name: ghcr
