apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-configmap
  namespace: default
  labels:
    app: kafka-ui-configmap
data:
  config.yml: |-
    kafka:
      clusters:
        - name: apk-cluster
          bootstrapServers: "apk-cluster-kafka-bootstrap:9092"
    kafka-connect:
      clusters:
        - name: apk-connect-cluster
          url: "http://connect-app:8083"      
    auth:
      type: disabled
    management:
      health:
        ldap:
          enabled: false