apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-configmap
  namespace: default
  labels:
    app: kafka-ui-configmap
data:
  config.yml: |-
    kafka:
      clusters:
        - name: yaml
          bootstrapServers: "apk-cluster-kafka-bootstrap:9092"
    auth:
      type: disabled
    management:
      health:
        ldap:
          enabled: false