apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-configmap
  namespace: default
  labels:
    app: kafka-ui-configmap
data:
  config.yml: |-
    kafka:
      clusters:
        - name: apk-cluster
          bootstrapServers: "apk-cluster-kafka-bootstrap:9092"
          schemaRegistry: "http://schema-registry:8081"
          kafkaConnect:
            - address: "http://connect-app:8083"
              name: "connect-app"
       
    auth:
      type: disabled
    management:
      health:
        ldap:
          enabled: false